build:
  verbosity: detailed

build_script:
  - gradlew.bat build

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk17

matrix:
  fast_finish: true